config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses do
    resources :lessons
  end 
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'home/activity'
  root 'home#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable, :confirmable
         
  rolify
  
  def to_s
    email
  end
  
  def username
      self.email.split(/@/).first
  end
  
  has_many :courses
  
  extend FriendlyId
  friendly_id :email, use: :slugged
  
  after_create :assign_default_role
  
  
  def assign_default_role
    if User.count == 1
      self.add_role(:admin) if self.roles.blank?
      self.add_role(:teacher)
      self.add_role(:student)
    else
      self.add_role(:student) if self.roles.blank?
      self.add_role(:teacher)
    end
  end
  
  validate :must_have_a_role, on: :update
  
  def online?
    updated_at > 2.minutes.ago
  end
  
  private
  def must_have_a_role
    unless roles.any?
      errors.add(:roles, "must have at least one role")
    end
  end 
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  
  
  def index
    @users = User.all.order(created_at: :desc)
    
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true)
  end
  
  def show
  end
  
  def edit
    authorize @user
  end
  
  def update
    authorize @user
    if @user.update(user_params)
      redirect_to users_path, notice: 'User #{@user.email} was successfully updated.'
    else
      render :edit
    end
  end
  
  private
  
  def set_user
    @user = User.friendly.find(params[:id])
  end
  
  def user_params
    params.require(:user).permit({role_ids: []})
  end
end

app/views/users/_user.html.haml
.card
   .card-header
      .fa.fa-user
      - if user.online?
         .text-success.fa.fa-circle
      - else
         .text-danger.fa.fa-circle
      = link_to user.email, user_path(user)
      
   .card-footer
      Signed Up
      = time_ago_in_words(user.created_at)
      ago
   .card-footer
      = 'sign_in_count'.humanize
      = user.sign_in_count
      .row
      = 'current_sign_in_at'.humanize
      = user.current_sign_in_at
      .row
      = 'last_sign_in_at'.humanize
      = user.last_sign_in_at
      .row
      = 'current_sign_in_ip'.humanize
      = user.current_sign_in_ip
      .row
      = 'last_sign_in_ip'.humanize
      = user.last_sign_in_ip
   .card-footer
      Confirmed email?
      - if user.confirmed_at.present?
         .badge.badge-success Yes
      - else
         .badge.badge-danger No
   .card-footer
      - user.roles.each do |role|
         .badge.badge.info
            = role.name
      - if policy(user).edit?
         = link_to 'Edit roles', edit_user_path(user), class: 'btn btn-sm btn-warning'
         

app/views/users/edit.html.haml
.card
   .card-header
      Editing roles for
      = @user.email
   .card-body
      = simple_form_for @user do |f|
         = f.collection_check_boxes :role_ids, Role.all, :id, :name
         = f.error :roles, class: 'text-danger'
         %hr
         = f.button :submit, class: "btn btn-danger"
   .card-footer
      = link_to 'Cancel', users_path, class: 'btn btn-danger'

app/views/users/index.html.haml
%h2
   .text-center
      Users
      .badge.badge-info
         = @users.count

%p
.card-columns
   - @users.each do |user|
      = render 'users/user', user: user
      

.form-inline
   = search_form_for @q do |f|
      = f.search_field :email_cont, placeholder: 'email'
      = f.search_field :sign_in_count_eq, placeholder: 'sign_in_count'
      = f.search_field :email_or_sign_in_count_eq, placeholder: 'email or sign_in_count'
      = f.submit
   .ml-2
   = link_to 'Refresh', users_path
   
%br


%table.table.table-bordered
   %thead
      %tr
         %th id
         %th= sort_link(@q, :email)
         %th created_at
         %th= 'sign_in_count'.humanize
         %th= 'current_sign_in_at'.humanize
         %th= 'last_sign_in_at'.humanize
         %th= 'current_sign_in_ip'.humanize
         %th= 'last_sign_in_ip'.humanize
   %tbody
      -@users.each do |user|
         %tr
            %td= user.id
            %td= user.email
            %td= user.created_at
            %td= user.sign_in_count
            %td= user.current_sign_in_at
            %td= user.last_sign_in_at
            %td= user.current_sign_in_ip
            %td= user.last_sign_in_ip

app/views/users/show.html.haml
= render 'users/user', user: @user