config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses do
    resources :lessons
  end 
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'home/activity'
  root 'home#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  validates :title, :content, :course, presence: true
  
  has_rich_text :content
  
  extend FriendlyId
  friendly_id :title, use: :slugged
  
  include PublicActivity::Model
  tracked owner: Proc.new{ |controller, model| controller.current_user}
  
  def to_s
    title
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
    authorize @lesson
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
    @course = Course.friendly.find(params[:course_id])
  end

  # GET /lessons/1/edit
  def edit
    authorize @lesson
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)
    @course = Course.friendly.find(params[:course_id])
    @lesson.course_id = @course_id

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to course_lesson_path(@course, @lesson), notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: course_lesson_path(@course, @lesson).errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    authorize @lesson
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to course_lesson_path(@course, @lesson), notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: course_lesson_path(@course, @lesson).errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    authorize @lesson
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @course = Course.friendly.find(params[:course_id])
      @lesson = Lesson.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lesson_params
      params.require(:lesson).permit(:title, :content, :course_id)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.haml
-# frozen_string_literal: true
= simple_form_for([@course,@lesson]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    /= f.input :content
    = f.label :content
    = f.rich_text_area :content
    /= f.association :course
    /= f.input :course_id, input_html: {value: @lesson.course_id || params[:course_id]}, as: :hidden

  .form-actions
    = f.button :submit

app/views/lessons/_lesson.html.haml
.card
   .card-header
      = link_to lesson.title, course_lesson_path(@course,lesson)
   - if policy(lesson).show?
      .card-body
         = lesson.content
         = lesson.course
   
   - if policy(lesson).edit?
      .card-footer
         = link_to 'Edit', edit_course_lesson_path(@course,lesson), class: 'btn btn-sm btn-warning'
         = link_to 'Destroy', [@course,lesson], method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' 
%p

app/views/lessons/edit.html.haml
%h1 Editing lesson

= render 'form'

= link_to 'Show lesson', course_lesson_path(@course, @lesson)
\|
= link_to 'Back to course', course_path(@lesson.course)

app/views/lessons/index.html.haml
%h1 Listing lessons

%table
  %thead
    %tr
      %th Title
      %th Content
      %th Course
      %th
      %th
      %th

  %tbody
    - @lessons.each do |lesson|
      %tr
        %td= lesson.title
        %td= lesson.content
        %td= lesson.course
        %td= link_to 'Show', lesson
        %td= link_to 'Edit', edit_lesson_path(lesson)
        %td= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Lesson', new_lesson_path

app/views/lessons/new.html.haml
%h1 New lesson

= render 'form'

= link_to 'Back', course_path(@course)

app/views/lessons/show.html.haml
/Adding the Breadcrumb in Lesson
= link_to 'Courses', courses_path
\|
= link_to @lesson.course.title, course_path(@lesson.course)
\|
= link_to @lesson.title,course_lesson_path(@course, @lesson)
%p

= render 'lessons/lesson', lesson: @lesson

/= link_to 'Back to course', course_path(@lesson.course)