config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :courses do
    resources :lessons
  end 
  resources :users, only: [:index, :edit, :show, :update]
  get 'home/index'
  get 'home/activity'
  root 'home#index'
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    #if params[:title]
      #@courses = Course.where('title ILIKE ?', "%#{params[:title]}%") #case-insensitive
    #else
      #@courses = Course.all
      #@q = Course.ransack(params[:q])
      #@courses = @q.result.includes(:user)
    #end
    @ransack_courses = Course.ransack(params[:courses_search], search_key: :courses_search)
    @courses = @ransack_courses.result.includes(:user)
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    authorize @course
    @lessons = @course.lessons
    
  end

  # GET /courses/new
  def new
    @course = Course.new
    authorize @course

  end

  # GET /courses/1/edit
  def edit
    authorize @course
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)
    authorize @course
    @course.user = current_user
    
    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    authorize @course
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    authorize @course
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description, :short_description, :language, :level, :price)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_course.html.haml
.card
    .card-header
        .fa.fa-graduation-cap
        = link_to course.title, course_path(course)
    .card-body
    %small= simple_format(course.short_description)
    .card-footer
        .text-center
            = number_to_currency(course.price)
    .card-footer
        .fa.fa-book
        = course.lessons.count
    .card-footer
        .row
            .col-md-6
                .fa.fa-globe-africa
                = course.language
            .col-md-6
                .text-right
                    .fa.fa-signal
                    = course.level
    
    .card-footer
        .row
            .col-md-6
                .far.fa-clock
                = course.created_at.strftime('%d-%b-%Y')
            .col-md-6
                .text-right
                    .fa.fa-chalkboard-teacher
                    = link_to course.user.username, user_path(course.user)
    - if current_user
        - if policy(course).edit?
            .card-footer
                /- if policy(course).edit?
                = link_to 'Edit', edit_course_path(course), class: 'btn btn-sm btn-warning' 
                /- if policy(course).destroy?
                = link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' 
                            

app/views/courses/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@course) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :title
    = f.label :description
    = f.rich_text_area :description
    %small= f.error :description,class: 'text-danger'
    = f.input :short_description
    = f.input :language, collection: Course.languages, include_blank:true
    = f.input :level, collection: Course.levels, include_blank:true
    = f.input :price

  .form-actions
    = f.button :submit

app/views/courses/edit.html.haml
.card
    .card-header
        %h1 Editing course
    .card-body
        = render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
%h2
  .text-center
    Courses
    .badge.badge-info
      = @courses.count
%p
.row
  .col-md-2
    .form-inline
      = search_form_for @ransack_courses, as: :courses_search, url: courses_path do |f|
        =f.label :title
        = f.search_field :title_cont, placeholder: 'Title', class: 'form-control form-control-sm'
        = f.label :description
        = f.search_field :short_description_cont, placeholder: 'Description', class: 'form-control form-control-sm'
        = f.label :language
        = f.select :language_cont, Course.languages, include_blank: true
        = f.label :level
        = f.select :level_cont, Course.levels, include_blank: true
        = f.label :price
        = f.search_field :price_eq, placeholder: 'Price', class: 'form-control form-control-sm'
        = f.label :teacher
        = f.search_field :user_email_cont, placeholder: 'Email', class:'form-control form-control-sm'
        = f.submit
      = link_to 'Refresh', courses_path
  
  .col-md-10
    .card-columns
      - @courses.each do |course|
        = render 'courses/course', course: course
%br

app/views/courses/new.html.haml
.card
    .card-header
        %h1 New course
    .card-body
        = render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.haml
= link_to 'Courses', courses_path
\|
= link_to @course.title, course_path(@course)
%p

.row
   .col-lg-6 
      = render 'courses/course', course: @course
   .col-lg-6
      = link_to 'Add lesson', new_course_lesson_path(@course, @lesson)
      - @lessons.each do |lesson|
         = render 'lessons/lesson', lesson: lesson